(function ensightenInit(){var ensightenOptions = {client: "citi", clientId: 1129, publishPath: "na_prod", isPublic:0, serverComponentLocation: "nexus.ensighten.com/citi/na_prod/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/citi/na_prod/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "true", enablePagePerfBeacon : "true", registryNs : "ensBootstraps", generatedOn : "Thu Mar 02 21:16:27 GMT 2017", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function l(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function m(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,c=0;c<a;c++){var d=b.dataDefinitions[b.dataDefinitionIds[c]];if(!d||
null==d.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var d={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};d.version="1.26.0";d.nexus=f.nexus||"nexus.ensighten.com";d.rand=-1;d.currSec=(new Date).getSeconds();d.options={interval:f.interval||100,erLoc:f.errorLocation||d.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||d.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||d.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||d.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};d.ruleList=[];d.allDeploymentIds=[];d.runDeploymentIds=[];d.runRuleIds=[];d.exceptionList=[];d.ensightenVariables={};d.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=l;d.DependencyNotAvailableException=l;m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;d.BeaconException=m;d.checkForInvalidDependencies=function(a,e,c,h){for(a=0;a<c.length;a++)if("DEPENDENCYNEVERAVAILABLE"===c[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new d.DependencyNotAvailableException(h[a])),e&&-1!==e&&d.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(d.currSec||0)%20,c=d.options.beaconSamplingSeedValue;-1===c?a=!0:0!==b&&0===c%b&&(a=!0)}catch(h){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+d.options.scLoc,!1,a||!0,d.options.scUseCacheBuster)};b.setVariable=function(a,b){d.ensightenVariables[a]=
b};b.getVariable=function(a){return a in d.ensightenVariables?d.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<d.ruleList.length;a++)d.test(d.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();d.exceptionList.push(a);a=window.location.protocol+"//"+d.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(d.options.clientId||-1)+"&client="+encodeURIComponent(d.options.client||"")+"&publishPath="+encodeURIComponent(d.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(e){window[ensightenOptions.ns].reportException(e)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&(d.runDeploymentIds.push(this.deploymentId),d.runRuleIds.push(this.id)),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;d.ruleList.push(a);
-1!==a.deploymentId&&d.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<d.ruleList.length;b++)if(d.ruleList[b].id===a)return d.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return d.allDeploymentIds};b.getRunRuleIds=function(){return d.runRuleIds};b.getRunDeploymentIds=function(){return d.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:
!1};d.toTwoChar=function(a){return(2===a.toString().length?"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+d.toTwoChar(b.getMonth())+"-"+d.toTwoChar(b.getDate())+" "+d.toTwoChar(b.getHours())+":"+d.toTwoChar(b.getMinutes())+":"+d.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);
this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=b.imageRequest(window.location.protocol+"//"+d.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+d.options.clientId+"&client="+d.options.client+"&publishPath="+d.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,c,h){var n=
document.getElementsByTagName("script"),g;h=void 0!==h?h:!0;if(void 0!==e?e:1)for(g=0;g<n.length;g++)if(n[g].src===a&&n[g].readyState&&/loaded|complete/.test(n[g].readyState))return;if(c){c=1==c&&"object"==typeof b.scDataObj?b.scDataObj:c;d.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;"object"===typeof c&&c.PageID&&(e=c.PageID,delete c.PageID);if("object"===typeof c)for(g in c){g=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,g.length?e.length-g.length:
e.length);e+=~e.indexOf("?")?"&":"?";for(k in c)e+=k+"="+c[k]+"&";e=e.slice(0,-1)+g;break}a+="?";h&&(a+="r="+d.rand+"&");a+="ClientID="+encodeURIComponent(d.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var c=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in c){if(!c[0]){setTimeout(arguments.callee,25);return}c=c[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.insertBefore(a,
c.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,c){var e=document.getElementsByTagName("script"),d;c=e[0];for(d=0;d<e.length;d++)if(e[d].src===a&&e[d].readyState&&/loaded|complete/.test(e[d].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}e=document.createElement("script");e.type="text/javascript";e.async=!0;e.src=a;e.onerror=function(){this.addEventListener&&(this.readyState="loaded")};e.onload=e.onreadystatechange=function(){if(!this.readyState||
"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&(this.readyState="loaded");try{b.call(this)}catch(g){window[ensightenOptions.ns].reportException(g)}}};c.parentNode.insertBefore(e,c)};b.unobtrusiveAddEvent=function(a,b,c){try{var e=a[b]?a[b]:function(){};a[b]=function(){c.apply(this,arguments);return e.apply(this,arguments)}}catch(n){window[ensightenOptions.ns].reportException(n)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=
e?e:"anonymous",a()}catch(c){window[ensightenOptions.ns].reportException(c)}}};b.setCurrentRuleId=function(a){b.currentRuleId=a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindOnGetServerComponent=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,c){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:c||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],
code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,c=0;c<a.length;++c)if(e=b.getRule(parseInt(a[c],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,c,h,f){var g=[];if(!d.checkForInvalidDependencies(e,h,c,f)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMLoaded=function(a,e,c,h,f){var g=[];if(!d.checkForInvalidDependencies(e,h,c,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,c,h,f){var g=[];if(!d.checkForInvalidDependencies(e,
h,c,f)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,c,h,f){var g=[];if(!d.checkForInvalidDependencies(e,h,c,f)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,c,h,f){var g=[];if(!d.checkForInvalidDependencies(e,h,c,f)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:h||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,c,f,n){var g=[];if(!d.checkForInvalidDependencies(e,f,c,n)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(c)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:f||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,c=0;c<e;c++){var d=a[c];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(d)&&b.dataDefinitionIds.push(d);else{for(var f=!1,g=b.dataDefinitionIds.length,l=0;l<g;l++)if(b.dataDefinitionIds[l]===d){f=!0;break}f||b.dataDefinitionIds.push(d)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=
a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var c=b.dataDefinitions[e];c||(c=new b.DataDefinition(e,a),b.dataDefinitions[e]=c);c.startRegistrationTime||(c.startRegistration(),c.registrationFn(),c.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=
!0;b.testAll()};b.callOnDOMParsed=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,c=a.length;b<c;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=
a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=
function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};var r=function(){var a=[],b=!1,c=!1;return{add:function(e){b&&!c?e():"function"==typeof e&&(a[a.length]=e)},exec:function(){c=!0;do{var e=a;a=[];b=!0;for(var d=0;d<e.length;d++)try{e[d].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);c=!1},haveRun:function(){return b}}};b.new_fArray=
function(){return r()};d.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?
d.timer=window.setInterval(function(){/loaded|interactive|complete/.test(document.readyState)&&(clearInterval(d.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(e){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",
function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===d.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,c,h,l,g=0;g<d.ruleList.length;++g)c=d.ruleList[g],h=c.executionData.hasRun?"1":"0",l=c.deploymentId.toString()+"|"+c.id.toString()+"|"+h,a.push(l);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+d.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+
"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+e+"&idx=0&r="+d.rand;b.imageRequest(m)}catch(q){b.currentRuleId=-1,b.currentDeploymentId=-1,a=new d.BeaconException(q),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,d.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},l,m=f.navigationStart||0,p,d={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"};l="&ns="+encodeURIComponent(f.navigationStart);for(var b in d)void 0!==f[b]?(p=f[b]-m,l+="&"+d[b]+"="+(0<p?encodeURIComponent(p):0)):l+="&"+d[b]+"=-1";window[ensightenOptions.ns].timing=l;b=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";l=f.indexOf(".com/");m=f.indexOf("/code/");f=f.substring(l+4,m)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+f)}}});
	
if (!window[ensightenOptions.ns].data) {
/*
 MIT License (c) copyright 2011-2013 original author or authors  MIT License (c) copyright 2013 original author or authors */
window.JSON&&"object"===typeof JSON||(window[ensightenOptions.ns].JSON={});
(function(){function c(a){return 10>a?"0"+a:a}function m(a){h.lastIndex=0;return h.test(a)?'"'+a.replace(h,function(a){var d=g[a];return"string"===typeof d?d:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function l(g,d){var c,b,e,p,h=k,u,t=d[g];t&&"object"===typeof t&&"function"===typeof t.toJSON&&(t=t.toJSON(g));"function"===typeof f&&(t=f.call(d,g,t));switch(typeof t){case "string":return m(t);case "number":return isFinite(t)?String(t):"null";case "boolean":case "null":return String(t);
case "object":if(!t)return"null";k+=a;u=[];if("[object Array]"===Object.prototype.toString.apply(t)){p=t.length;for(c=0;c<p;c+=1)u[c]=l(c,t)||"null";e=0===u.length?"[]":k?"[\n"+k+u.join(",\n"+k)+"\n"+h+"]":"["+u.join(",")+"]";k=h;return e}if(f&&"object"===typeof f)for(p=f.length,c=0;c<p;c+=1)"string"===typeof f[c]&&(b=f[c],(e=l(b,t))&&u.push(m(b)+(k?": ":":")+e));else for(b in t)Object.prototype.hasOwnProperty.call(t,b)&&(e=l(b,t))&&u.push(m(b)+(k?": ":":")+e);e=0===u.length?"{}":k?"{\n"+k+u.join(",\n"+
k)+"\n"+h+"}":"{"+u.join(",")+"}";k=h;return e}}var b=window.JSON?window.JSON:window[ensightenOptions.ns].JSON;"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+c(this.getUTCMonth()+1)+"-"+c(this.getUTCDate())+"T"+c(this.getUTCHours())+":"+c(this.getUTCMinutes())+":"+c(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var e=
/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,h=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,k,a,g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},f;"function"!==typeof b.stringify&&(b.stringify=function(c,d,b){var g;a=k="";if("number"===typeof b)for(g=0;g<b;g+=1)a+=" ";else"string"===typeof b&&(a=b);if((f=d)&&"function"!==typeof d&&
("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON.stringify");return l("",{"":c})});"function"!==typeof b.parse&&(b.parse=function(a,d){function c(a,b){var g,f,e=a[b];if(e&&"object"===typeof e)for(g in e)Object.prototype.hasOwnProperty.call(e,g)&&(f=c(e,g),void 0!==f?e[g]=f:delete e[g]);return d.call(a,b,e)}var b;a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return b=eval("("+a+")"),"function"===typeof d?c({"":b},""):b;throw new SyntaxError("JSON.parse");})})();
window[ensightenOptions.ns].when=function(){function c(a,d,b,c){return l(a).then(d,b,c)}function m(a){this.then=a}function l(a){return b(function(d){d(a)})}function b(d){function c(a){r&&(p=e(a),g(r,p),r=w)}function f(a){c(k(a))}function n(d){r&&g(r,a(d))}var p,r=[];try{d(c,f,n)}catch(H){f(H)}return new m(function(a,d,c){return b(function(b,f,g){r?r.push(function(e){e.then(a,d,c).then(b,f,g)}):q(function(){p.then(a,d,c).then(b,f,g)})})})}function e(a){return a instanceof m?a:a!==Object(a)?h(a):b(function(d,
c,b){q(function(){try{var f=a.then;"function"===typeof f?B(f,a,d,c,b):d(h(a))}catch(A){c(A)}})})}function h(a){var d=new m(function(c){try{return"function"==typeof c?e(c(a)):d}catch(G){return k(G)}});return d}function k(a){var d=new m(function(c,b){try{return"function"==typeof b?e(b(a)):d}catch(I){return k(I)}});return d}function a(d){var c=new m(function(b,f,g){try{return"function"==typeof g?a(g(d)):c}catch(A){return a(A)}});return c}function g(a,d){q(function(){for(var c,b=0;c=a[b++];)c(d)})}function f(a,
d,f,g,e){r(2,arguments);return c(a,function(a){return b(function(b,f,g){function e(a){k(a)}function q(a){h(a)}var n,p,r,t,h,k,l,z;l=a.length>>>0;n=Math.max(0,Math.min(d,l));r=[];p=l-n+1;t=[];if(n)for(k=function(a){t.push(a);--p||(h=k=v,f(t))},h=function(a){r.push(a);--n||(h=k=v,b(r))},z=0;z<l;++z)z in a&&c(a[z],q,e,g);else b(r)}).then(f,g,e)})}function p(a,c,b,f){r(1,arguments);return d(a,E).then(c,b,f)}function d(a,d){return c(a,function(a){return b(function(b,f,g){var e,q,n,p,r;n=q=a.length>>>0;
e=[];if(n)for(p=function(a,q){c(a,d).then(function(a){e[q]=a;--n||b(e)},f,g)},r=0;r<q;r++)r in a?p(a[r],r):--n;else b(e)})})}function q(a){1===x.push(a)&&C(n)}function n(){for(var a,d=0;a=x[d++];)a();x=[]}function r(a,d){for(var c,b=d.length;b>a;)if(c=d[--b],null!=c&&"function"!=typeof c)throw Error("arg "+b+" must be a function");}function v(){}function E(a){return a}c.defer=function(){var a,d,c;a={promise:w,resolve:w,reject:w,notify:w,resolver:{resolve:w,reject:w,notify:w}};a.promise=d=b(function(b,
f,g){a.resolve=a.resolver.resolve=function(a){if(c)return l(a);c=!0;b(a);return d};a.reject=a.resolver.reject=function(a){if(c)return l(k(a));c=!0;f(a);return d};a.notify=a.resolver.notify=function(a){g(a);return a}});return a};c.resolve=l;c.reject=function(a){return c(a,k)};c.join=function(){return d(arguments,E)};c.all=p;c.map=d;c.reduce=function(a,d){var b=B(t,arguments,1);return c(a,function(a){var f;f=a.length;b[0]=function(a,b,g){return c(a,function(a){return c(b,function(b){return d(a,b,g,
f)})})};return u.apply(a,b)})};c.any=function(a,d,b,c){return f(a,1,function(a){return d?d(a[0]):a[0]},b,c)};c.some=f;c.isPromise=function(a){return a&&"function"===typeof a.then};m.prototype={otherwise:function(a){return this.then(w,a)},ensure:function(a){function d(){return l(a())}return this.then(d,d).yield(this)},yield:function(a){return this.then(function(){return a})},spread:function(a){return this.then(function(d){return p(d,function(d){return a.apply(w,d)})})},always:function(a,d){return this.then(a,
a,d)}};var u,t,B,C,x,F,y,D,w;x=[];F=setTimeout;C="function"===typeof setImmediate?"undefined"===typeof window?setImmediate:setImmediate.bind(window):"object"===typeof process&&process.nextTick?process.nextTick:function(a){F(a,0)};y=Function.prototype;D=y.call;B=y.bind?D.bind(D):function(a,d){return a.apply(d,t.call(arguments,2))};y=[];t=y.slice;u=y.reduce||function(a){var d,b,c,f;f=0;d=Object(this);c=d.length>>>0;b=arguments;if(1>=b.length)for(;;){if(f in d){b=d[f++];break}if(++f>=c)throw new TypeError;
}else b=b[1];for(;f<c;++f)f in d&&(b=a(b,d[f],f,d));return b};return c}();
(function(){function c(b,c){return l.all(c||[],function(c){return b.apply(null,c)})}function m(e){var h=b.call(arguments,1);return function(){return c(e,h.concat(b.call(arguments)))}}var l,b;l=window[ensightenOptions.ns].when;b=[].slice;l.apply=c;l.call=function(e){return c(e,b.call(arguments,1))};l.lift=m;l.bind=m;l.compose=function(e){var h=b.call(arguments,1);return function(){var k=b.call(arguments),k=c(e,k);return l.reduce(h,function(a,b){return b(a)},k)}}})();
window[ensightenOptions.ns].data=function(c,m){function l(a,b){this.name="DataDefinitionException";this.message=b||"Data definitions cannot be resolved as there are invalid id(s): "+a}var b={engines:{memory:{get:function(a){if(e.utils.isArray(a)){for(var g=[],f=0;f<a.length;f++)g.push(b.data[a[f]]);return c[ensightenOptions.ns].when.resolve(g)}g=b.dataDefinitions[a]||{storage:{get:function(){}}};g=g.storage.get(g);b.data[a]=g;return c[ensightenOptions.ns].when.resolve(b.data[a])},set:function(a,g){if(e.utils.isArray(a))for(var f in a)b.data[a[f]]=
g[f];else b.data[a]=g;return c[ensightenOptions.ns].when.resolve(!0)},remove:function(a){if(e.utils.isArray(a))for(var g in a)delete b.data[a[g]];else delete b.data[a];return c[ensightenOptions.ns].when.resolve(!0)},clear:function(a){b.data={};b.definitions={};return c[ensightenOptions.ns].when.resolve(!0)},all:function(){return c[ensightenOptions.ns].when.resolve(b.data)}}},normalizeInputArgs:function(a,b){var c={key:[],val:m},g;if(e.utils.isPlainObject(a))for(g in c.val=[],a)c.key.push(g),c.val.push(a[g]);
else e.utils.isArray(a),c.key=a,c.val=b;return c},definitions:{},data:{}},e={utils:{isPlainObject:function(a){return!!a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"[object Array]"===Object.prototype.toString.call(a)},escapeRegEx:function(a){try{return a.replace(/([.*+?^${}()|\[\]\/\\])/g,"\\$1")}catch(g){return a}}}},h=function(){return c[ensightenOptions.ns].when.reject("Not Implemented.")};l.prototype=Error();l.prototype||(l.prototype={});l.prototype.constructor=
l;b.DataDefinitionException=l;b.checkForInvalidDataDefinitions=function(a){e.utils.isArray(a)||(a=[a]);return a&&0<a.length&&(a=a.join(","),-1<a.indexOf("invalid_id"))?(c[ensightenOptions.ns].reportException(new b.DataDefinitionException(a)),!0):!1};b.collectAvailableDataDefinitions=function(a){for(var g=[],f=0;f<a.length;f++){var p=parseInt(a[f],10),d=c[ensightenOptions.ns].dataDefinitions[p];if(null===d||d===m)if(d=e.storage.session.get({id:p}),null!==d&&d!==m)e.set(p,d),b.dataDefinitions[p]={id:p,
load:"visitor",storage:e.storage.visitor,missingDDFromCache:!0},g.push(c[ensightenOptions.ns].data.get(""+p));else return c[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Invalid data definition used: "+p)),{promises:[],isInvalid:!0};else g.push(c[ensightenOptions.ns].data.get(a[f]))}return{promises:g,isInvalid:!1}};b.getSync=function(a){function g(a){var b=a.extract||p,c=a.transform||d,g=!1,e=null,q=null;try{e=b()}catch(x){e=null,g=!0}try{q=c(e)}catch(x){q=null,g=!0}g&&f.push(a.id);
return q}var f=[],p=function(){return document},d=function(a){return null!==a&&a!==m?a.toString():null},q=parseInt(a);a="string"===typeof a?a.split("."):[];var n={},r="";isNaN(q)?3==a.length&&(n=e.getDataDefinitionBySourceCollectionName(a[0],a[1],a[2])):n=e.getDataDefinitionById(q);r=n.load&&n.load.match(/(session|visitor)/i)&&n.storage&&n.storage.get?n.storage.get(n):g(n);0<f.length&&c[ensightenOptions.ns].reportException(new b.DataDefinitionException(f,"Error resolving data definitions synchronously: "+
f));return r};b.dataDefinitions={};b.dataDefinitionsBySourceCollName={};e.defineEngine=function(a,g){var f,e=["get","set","remove","clear","all"];b.engines[a]=g;if(!g.returnsPromise)for(f=0;f<e.length;f++){var d=e[f];g[d]=c[ensightenOptions.ns].when.lift(g[d])}};e.storage={instance:{set:function(a,b){},get:function(a){return b.getSync(a.id)}},page:{set:function(a,b){},get:function(a){return b.data[a.id]}},session:{set:function(a,b){var f=e.storage.session.get({id:a}),g=new Date,d=g.getTime();g.setTime(d+
18E5);null!=f&&(b=f);c[ensightenOptions.ns].data.cookie.utils.set(a,b,{expires:g.toGMTString()});f={expires:g.getTime(),value:b};c[ensightenOptions.ns].data.local.utils.set(a,f)},get:function(a){var b=c[ensightenOptions.ns].data.cookie.utils.get(a.id),f=c.JSON&&c.JSON.stringify?c.JSON:c[ensightenOptions.ns].JSON,f=f||{},e,d=new Date,d=d.getTime();if(null===b){try{e=f.parse(c[ensightenOptions.ns].data.local.utils.get(a.id))}catch(q){e=null}null!=e&&(e.expires=+e.expires,d<=e.expires?b=e.value:""==
e.expires&&e.value!=m?b=e.value:c[ensightenOptions.ns].data.local.utils.remove(a.id))}return b}},visitor:{set:function(a,b){var f=e.storage.session.get({id:a});null!=f&&(b=f);c[ensightenOptions.ns].data.cookie.utils.set(a,b);c[ensightenOptions.ns].data.local.utils.set(a,{expires:"",value:b})},get:function(a){return e.storage.session.get(a)}}};e.getEngine=e.engine=function(a){return a?b.engines[a]||{get:h,set:h,remove:h,clear:h,all:h}:b.engines};e.all=function(a){return c[ensightenOptions.ns].data.engine(a||
"memory").all()};e.get=function(a,e,f){e=e||"memory";f=f||{};-1<a.indexOf(",")&&(a=a.split(","));a=b.normalizeInputArgs(a);return f.wait?b.getWait(a.key,c[ensightenOptions.ns].data.engine(e),f):b.data&&b.data.hasOwnProperty(a.key)?c[ensightenOptions.ns].data.engine(e).get(a.key):b.getWaitForKey(a.key,c[ensightenOptions.ns].data.engine(e),f)};b.getWait=function(a,b,f){var g=+new Date,d=c[ensightenOptions.ns].when.defer(),q=function(){var c=b.get(a);if(-1===f.wait)return c;c.then(function(a){f.setCheck(a)?
d.resolve(a):setTimeout(n,f.interval)},function(a){setTimeout(n,f.interval)})},n=function(){var a=+new Date-g;-1!==f.wait&&a<f.wait?q():d.reject("Timeout")};f.interval=f.interval||500;f.wait=f.wait||5E3;e.utils.isArray(a)?f.setCheck=f.setCheck||function(a){for(var b=!0,d=0;d<a.length;d++)b=b&&!!a[d];return b}:f.setCheck=f.setCheck||function(a){return!!a};q();return d.promise};b.getWaitForKey=function(a,e,f){var g=c[ensightenOptions.ns].when.defer(),d=function(){if(b.data&&b.data.hasOwnProperty(a)){var d=
e.get(a);if(-1===f.wait)return d;d.then(function(a){g.resolve(a)},function(a){g.reject(a)})}else setTimeout(q,f.interval)},q=function(){d()};f.interval=f.interval||100;f.wait=f.wait||1;d();return g.promise};e.set=function(a,e,f){var g=b.normalizeInputArgs(a,e);Array.prototype.slice.call(arguments);return c[ensightenOptions.ns].data.engine(f||"memory").set(g.key,g.val)};e.remove=function(a,b){return c[ensightenOptions.ns].data.engine(b||"memory").remove(a)};e.clear=function(a){return c[ensightenOptions.ns].data.engine(a||
"memory").clear()};e.define=function(a,g){g&&(a.name=g.id||g.name);if(!a.name)return c[ensightenOptions.ns].when.reject(Error("Invalid parameters: missing 'name'"));a.id=a.name;var f=a.load||"page";a.load=a.load||"javascript";a.load=-1<a.load.indexOf("javascript")?a.load:a.load+",javascript";a.trigger=a.trigger||function(){return c[ensightenOptions.ns].when.resolve()};a.priv=a.priv||!1;a.collection=a.collection||"Data Layer";a.persist=c[ensightenOptions.ns].data.engine("memory");a.storage=e.storage[f.toLowerCase()]||
e.storage.page;var h=a.extract||function(){return document},d=a.transform||function(a){return a},q=function(b,d){var e=[];e.push(a.persist.set(b,d));a.storage.set(a.id,d);"object"==typeof c[ensightenOptions.ns].data.dataExport&&c[ensightenOptions.ns].data.dataExport(b,d,a.collection);c[ensightenOptions.ns].when.all(e).then(function(a){n.resolve(a)},function(a){n.reject(a)})},n=c[ensightenOptions.ns].when.defer(),r;try{r=a.trigger()}catch(v){c[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,
'"'+v+'" error caught in Data Definition trigger: '+a.dataDefName+", ID:"+a.id+". Using bottom of body trigger.")),r=c[ensightenOptions.ns].data.bottomOfBodyTrigger()}r.then(function(){n.resolve(c[ensightenOptions.ns].when.reduce([function(){try{return h()}catch(v){return c[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,'"'+v+'" error caught in Data Definition extractor: '+a.dataDefName+", ID:"+a.id+".")),null}}(),function(){try{return d.apply(this,arguments)}catch(v){return c[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,
'"'+v+'" error caught in Data Definition transformer: '+a.dataDefName+", ID "+a.id+".")),null}},q],function(b,d,c,e){if(1==c)return d(b);2==c&&d(a.name,b)}))},function(a){n.reject(a)});b.dataDefinitions[a.id]=a;b.dataDefinitionsBySourceCollName[""+a.source+"."+a.collection+"."+a.dataDefName]=a;return n.promise};e.checkConditions=function(a){var g,f={lt:function(a,e){var d=+a,f=+e;return isNaN(d)||isNaN(f)?(c[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+
a+", compareTo: "+e)),!1):d<f},gt:function(a,e){var d=+a,f=+e;return isNaN(d)||isNaN(f)?(c[ensightenOptions.ns].reportException(new b.DataDefinitionException(null,"Value(s) cannot be converted to number: compareWith: "+a+", compareTo: "+e)),!1):d>f},eql:function(a,b){return a==b},exists:function(a,b){return null==a||a==m||""==a?!1:!0},re:function(a,b,c){b=new RegExp(b,c?"i":"");try{return a.match(b)}catch(r){return!1}},starts:function(a,b,c){b=e.utils.escapeRegEx(b);return f.re(a,"^"+b,c)},ends:function(a,
b,c){b=e.utils.escapeRegEx(b);return f.re(a,b+"$",c)},contains:function(a,b,c){b=e.utils.escapeRegEx(b);return f.re(a,".*"+b+".*",c)}};f.is=f.eql;f["starts with"]=f.starts;f["ends with"]=f.ends;f["is greater than"]=f.gt;f["is less than"]=f.lt;f.matches=f.re;for(g=0;g<a.values.length;g++){var h=(a.customComparator?a.customComparator[g]?a.customComparator[g]:f[a.comparators[g]]:f[a.comparators[g]])(a.values[g],a.compareTo[g],a.caseInsensitive?a.caseInsensitive[g]||!1:!1);a.not[g]&&(h=!h);if(!h)return!1}return!0};
e.triggerPromise=function(a,b,e){e=e||5E3;var f=+new Date,d=c[ensightenOptions.ns].when.defer();(function(){var c=a();c!=b?d.resolve(c):+new Date-f<e?setTimeout(arguments.callee,200):d.reject("timed out")})();return d.promise};e.timeoutPromise=function(a,b){var e=c[ensightenOptions.ns].when.defer();b=b||800;a.then(e.resolve,e.reject);setTimeout(function(){e.reject(Error("timed out"))},b);return e.promise};e.delayTrigger=function(a){a=a||10;var b=c[ensightenOptions.ns].when.defer();setTimeout(function(){b.resolve()},
a);return b.promise};e.delayUntilTrigger=function(a,b,e,h){e=e||null;h=h||200;var d=+new Date,f=c[ensightenOptions.ns].when.defer();(function(){var c=a();c!=b?f.resolve(c):e?+new Date-d<e?setTimeout(arguments.callee,h):f.reject("timed out"):setTimeout(arguments.callee,h)})();return f.promise};b.applyTrigger=function(a){var b=c[ensightenOptions.ns].when.defer();a(function(){b.resolve(!0)});return b.promise};e.immediateTrigger=function(){return b.applyTrigger(c[ensightenOptions.ns].bindImmediate)};
e.bottomOfBodyTrigger=function(){return b.applyTrigger(c[ensightenOptions.ns].bindDOMParsed)};e.whenValueExistsTrigger=function(){return c[ensightenOptions.ns].when.resolve(this.extract())};e.afterEnsightenCompleteTrigger=function(){return b.applyTrigger(c[ensightenOptions.ns].bindPageSpecificCompletion)};e.afterElementsDownloadedTrigger=function(){return b.applyTrigger(c[ensightenOptions.ns].bindDOMLoaded)};e.getAllDataDefinitionsOnCurrentPage=function(){return b.dataDefinitions};e.getAllDataDefinitionsOnCurrentPage_S_C_N=
function(){return b.dataDefinitionsBySourceCollName};e.getDataDefinitionById=function(a){return b.dataDefinitions[a||-1]||{}};e.getDataDefinitionBySourceCollectionName=function(a,c,e){return b.dataDefinitionsBySourceCollName[""+a+"."+c+"."+e]||{}};e.getDataDefinitionByPercentSyntax=function(a){a=(""+a).split("_");return 1>a.length?{}:b.dataDefinitions[a[1]]||{}};e.resolve=function(a,g){var f=this,h=null;if(!b.checkForInvalidDataDefinitions(a))if(g)c[ensightenOptions.ns].bindDataDefinitionComplete(function(){var d=
b.collectAvailableDataDefinitions(a);d.isInvalid||c[ensightenOptions.ns].when.all(d.promises).then(function(d){try{g.apply(f,d)}catch(v){c[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+v))}},function(d){c[ensightenOptions.ns].reportException(new b.DataDefinitionException(a,"Error resolving data definitions: "+a+". Details: "+d))})});else{var h=[],d=a;e.utils.isArray(a)||(d=[a]);for(var q=0;q<d.length;q++)h.push(b.getSync(d[q]));
return h=e.utils.isArray(a)?h:h[0]}};e.extract=function(a,b){var e="",g=function(a,b){var c=~b.indexOf("#")?b.split("#")[1]:"",d=c?0:~b.indexOf("[")?parseInt(b.match(/\[(\d+)\]/)[1]):0,e=(c?b.split("#")[0]:d?b.split("[")[0]:b).toLowerCase();if(a==document&&"html"==e&&0==d)return document.getElementsByTagName("html")[0];if(~b.indexOf("#"))return document.getElementById(b.split("#")[1]);var f=a.firstChild;if(!f)return null;for(var g=0,d=0!=d?d-1:d;f;){if(1==f.nodeType){if(f.tagName.toLowerCase()==e&&
""!=c&&f.id==c||f.tagName.toLowerCase()==e&&g==d&&""==c)return f;f.tagName.toLowerCase()==e&&g++}f=f.nextSibling}},d=function(a,b){a=a.split("/");for(var c=g(b||document,a[1]),d=2;d<a.length;d++){if(null==c)return null;c=g(c,a[d])}return c},q=function(){for(var a={},b=c.document.getElementsByTagName("META")||[],d=0,e=b.length;d<e;d++){var f=b[d].name||b[d].getAttribute("property")||"";0!==f.length&&(a[f]=b[d].content)}return a}(),n=function(a){var b=q[a];if(b)return b;for(var b=c.document.getElementsByTagName("META")||
[],d=0,e=b.length;d<e;d++){var f=b[d].name||b[d].getAttribute("property")||"";if(a==f)return b[d].content}},h=function(a){return(val=(new RegExp("&"+a+"=([^&]*)")).exec(c.location.search.replace(/^\?/,"&")))?val[0].split("=")[1]:""},k=function(a){return(val=(new RegExp("^"+a+"=.*|;\\s*"+a+"=.*")).exec(c.document.cookie))?val[0].split("=")[1].split(";")[0]:""},l=function(a){(a=m(a))&&a.nodeType&&1==a.nodeType&&(a=a.value||a.innerHTML||"");return a.toString().replace(/\n|\r|\s\s+/g,"")||""},m=function(a){var b=
"";if(0==a.indexOf("/HTML/BODY"))b=d(a);else try{b=eval(a)}catch(C){b=""}return b};try{return b?"meta"==b?e=n(a):"cookie"==b?e=k(a):"param"==b?e=h(a):"content"==b?e=l(a):"event"==b?e=m(a):"var"==b&&(e=c[a]):e=n(a)||k(a)||h(a)||l(a)||m(a)||c[a]||"",e||""}catch(t){return""}};if("undefined"==typeof k)var k={exports:{}};return e}(window);
window[ensightenOptions.ns].data.defineEngine("store",function(){var c={},m=window,l=m.document,b,e,h=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};c.set=function(a,b){};c.get=function(a){};c.remove=function(a){};c.clear=function(){};try{if("localStorage"in m&&m.localStorage)b=m.localStorage,c.set=function(a,c){var d,e,f=window.JSON&&window.JSON.stringify?window.JSON:window[ensightenOptions.ns].JSON;if(h(a))for(d=0,e=a.length;d<e;d++)b.setItem(a[d],"string"===
typeof c[d]?c[d]:f.stringify(c[d]));else b.setItem(a,"string"===typeof c?c:f.stringify(c))},c.get=function(a){if(h(a)){var c={},d,e;d=0;for(e=a.length;d<e;d++)c[a[d]]=b.getItem(a[d]);return c}return b.getItem(a)},c.remove=function(a){if(h(a)){var c,d;c=0;for(d=a.length;c<d;c++)b.removeItem(a[c])}else b.removeItem(a)},c.clear=function(){b.clear()},c.all=function(){return b};else if("globalStorage"in m&&m.globalStorage)b=m.globalStorage[m.location.hostname],c.set=function(a,c){if(h(a)){var d,e;d=0;
for(e=a.length;d<e;d++)b[a[d]]=c[d]}else b[a]=c},c.get=function(a){if(h(a)){var c={},d,e;d=0;for(e=a.length;d<e;d++)c[a[d]]=b[a[d]]&&b[a[d]].value;return c}return b[a]&&b[a].value},c.remove=function(a){if(h(a)){var c,d;c=0;for(d=a.length;c<d;c++)delete b[a[c]]}else delete b[a]},c.clear=function(){for(var a in b)delete b[a]},c.all=function(){return b};else if(l.documentElement.addBehavior){var k=function(a){return a.replace(f,"___")},m=function(c){return function(){var d=Array.prototype.slice.call(arguments,
0);d.unshift(b);a.appendChild(b);b.addBehavior("#default#userData");b.load("localStorage");d=c.apply(store,d);a.removeChild(b);return d}},a,g;try{g=new ActiveXObject("htmlfile"),g.open(),g.write('<script>document.w=window\x3c/script><iframe src="/favicon.ico"></frame>'),g.close(),a=g.w.frames[0].document,b=a.createElement("div")}catch(d){b=l.createElement("div"),a=l.body}var f=RegExp("[!\"#$%&'()*+,/\\\\:;<=>?@[\\]^`{|}~]","g");c.set=m(function(a,b,e){if(h(b)){var d,f;d=0;for(f=b.length;d<f;d++){fixedKey=
k(b[d]);if(void 0===e[d])return c.remove(fixedKey);a.setAttribute(fixedKey,e[d]);a.save("localStorage")}}else{fixedKey=k(b);if(void 0===e)return c.remove(fixedKey);a.setAttribute(fixedKey,e);a.save("localStorage")}});c.get=m(function(a,b){if(h(b)){var c={},d,e,f;e=0;for(f=b.length;e<f;e++)d=k(b[e]),c[b[e]]=a.getAttribute(d);return c}b=k(b);return a.getAttribute(b)});c.remove=m(function(a,b){if(h(b)){var c,e;c=0;for(e=b.length;c<e;c++)a.removeAttribute(k(b[c])),a.save("localStorage")}else b=k(b),a.removeAttribute(b),
a.save("localStorage")});c.clear=m(function(a){var b=a.XMLDocument.documentElement.attributes;a.load("localStorage");for(var c=0,e;e=b[c];c++)a.removeAttribute(e.name);a.save("localStorage")});c.all=m(function(a){for(var b=a.XMLDocument.documentElement.attributes,c={},e=0,d;d=b[e];++e){var f=k(d.name);c[d.name]=a.getAttribute(f)}return c})}}catch(d){}var p={};for(e in c)p[e]=c[e];p.testStorage=function(){try{var a="tk_"+Math.ceil(5E7*Math.random());p.set(a,"test");if("test"===p.get(a))return p.remove(a),
!0}catch(q){}return!1};c.utils=p;return window[ensightenOptions.ns].data.local=c}());
window[ensightenOptions.ns].data.defineEngine("cookie",function(c,m){var l=function(){return l.get.apply(l,arguments)},b=l.utils={isArray:Array.isArray||function(b){return"[object Array]"===Object.prototype.toString.call(b)},isPlainObject:window[ensightenOptions.ns].data.utils.isPlainObject,toArray:function(b){return Array.prototype.slice.call(b)},getKeys:Object.keys||function(b){var c=[],e="";for(e in b)b.hasOwnProperty(e)&&c.push(e);return c},escape:function(b){return String(b).replace(/[,;"\\=\s%]/g,
function(b){return encodeURIComponent(b)})},retrieve:function(b,c){return null==b?c:b},getAllCookies:function(){if(""===c.cookie)return{};for(var b=c.cookie.split("; "),h={},k=0,a=b.length;k<a;k++){var g=b[k].split("=");h[decodeURIComponent(g[0])]=decodeURIComponent(g[1])}return h},set:function(e,h,k){k=k||-1;if(b.isPlainObject(e))for(var a in e)e.hasOwnProperty(a)&&l.set(a,e[a],h);else if(b.isArray(e)){var g;a=0;for(g=e.length;a<g;a++)l.set(e[a],h[a],k)}else{a=k.expires!==m?k.expires:l.defaults.expires||
"";"number"===typeof a&&(a=new Date(a));a=b.isPlainObject(a)&&"toGMTString"in a?";expires="+a.toGMTString():b.isPlainObject(a)&&a instanceof Date?";expires="+a.toUTCString():";expires="+a;g=(g=k.path||l.defaults.path)?";path="+g:"";var f=k.domain||l.defaults.domain,f=f?";domain="+f:"";k=k.secure||l.defaults.secure?";secure":"";c.cookie=b.escape(e)+"="+b.escape(h)+a+g+f+k}},get:function(c,h){h=h||m;var e=b.getAllCookies();if(b.isArray(c)){for(var a={},g=0,f=c.length;g<f;g++)a[c[g]]=b.retrieve(e[c[g]],
h),a[c[g]]===m&&(a[c[g]]=null);return a}a=b.retrieve(e[c],h);return a===m?null:a},getGMTString:function(b){var c=new Date;c.setTime(c.getTime()+864E5*b);return c.toGMTString()}};l.defaults={path:"/",expires:b.getGMTString(90)};l.set=function(c,h){b.set(c,h)};l.remove=function(c){c=b.isArray(c)?c:b.toArray(arguments);for(var e=0,k=c.length;e<k;e++)b.set(c[e],"",{expires:-1})};l.clear=function(){return l.remove(b.getKeys(b.getAllCookies()))};l.get=function(c,h){return b.get(c,h)};l.all=function(){return b.getAllCookies()};
l.utils=b;return window[ensightenOptions.ns].data.cookie=l}(document));

}
		
window[ensightenOptions.ns].ensEvent=function(l,u){var k={queue:{},pollQueue:{},pushTrigger:function(b,g){if("[object Array]"===Object.prototype.toString.call(b)){for(var d=0;d<b.length;d++)k.pushTrigger(b[d],g);return!0}if("string"!=typeof b)return!1;this.queue[b]=this.queue[b]||{fn:[]};"function"==typeof g&&this.queue[b].fn.push(g);return!0},callTrigger:function(b,g,d){if("string"!=typeof b)return!1;b=k.queue[b];if("object"==typeof b&&b.fn&&b.fn.length&&(0!=b.fireOnFirstSet&&g==u||g!=u&&0!=b.fireOnUpdate))for(g=
0;g<b.fn.length;g++)b.fn[g].call(this)},setPollOptions:function(b,g,d){this.queue[b]=this.queue[b]||{fn:[]};this.queue[b].fireOnFirstSet=g;this.queue[b].fireOnUpdate=d},callPoll:function(b,g,d,l,t){if("string"==typeof b&&g&&g.length&&!(1>g.length)){for(var p=0;p<g.length;p++)k.setPollOptions(g[p],l,t);k.pushWatch(b,g,d)}},pushWatch:function(b,g,d){this.pollQueue[b]||(this.pollQueue[b]={previousVal:u,eventArr:[],valueFn:d});this.pollQueue[b].eventArr=this.pollQueue[b].eventArr.concat(g);this.pollQueue[b].valueFn=
d},globalWatch:function(){setInterval(function(){for(key in k.pollQueue){var b=k.pollQueue[key],g=b.valueFn(key);if(b.previousVal!==g){for(var d=0;d<b.eventArr.length;d++)k.callTrigger.call(l,b.eventArr[d],b.previousVal,g);k.pollQueue[key].previousVal=g}}},500)}};k.globalWatch();return{add:function(b,g){return k.pushTrigger(b,g)},get:function(b){return k.queue[b]},trigger:function(b,g){return k.callTrigger.call(g||l,b)},poll:function(b,g,d,u,t){t=t||l[ensightenOptions.ns].data.resolve;return k.callPoll(b,
g,t,d,u)}}}(window);
(function(l,u,k){u[l]=k()})("qwery",window[ensightenOptions.ns],function(){function l(){this.c={}}function u(a){return G.g(a)||G.s(a,"(^|\\s+)"+a+"(\\s+|$)",1)}function k(a,e){for(var f=0,c=a.length;f<c;f++)e(a[f])}function b(a){for(var e=[],f=0,c=a.length;f<c;++f)s(a[f])?e=e.concat(a[f]):e[e.length]=a[f];return e}function g(a){for(var e=0,f=a.length,c=[];e<f;e++)c[e]=a[e];return c}function d(a){for(;(a=a.previousSibling)&&1!=a.nodeType;);return a}function x(a){return a.match(N)}function t(a,e,f,
c,b,r,h,g,d,k,s){var n,y,l;if(1!==this.nodeType||e&&"*"!==e&&this.tagName&&this.tagName.toLowerCase()!==e||f&&(n=f.match(O))&&n[1]!==this.id)return!1;if(f&&(l=f.match(P)))for(a=l.length;a--;)if(!u(l[a].slice(1)).test(this.className))return!1;if(d&&m.pseudos[d]&&!m.pseudos[d](this,s))return!1;if(c&&!h)for(y in d=this.attributes,d)if(Object.prototype.hasOwnProperty.call(d,y)&&(d[y].name||y)==b)return this;return c&&!q(r,Q(this,b)||"",h)?!1:this}function p(a){return H.g(a)||H.s(a,a.replace(R,"\\$1"))}
function q(a,e,f){switch(a){case "=":return e==f;case "^=":return e.match(w.g("^="+f)||w.s("^="+f,"^"+p(f),1));case "$=":return e.match(w.g("$="+f)||w.s("$="+f,p(f)+"$",1));case "*=":return e.match(w.g(f)||w.s(f,p(f),1));case "~=":return e.match(w.g("~="+f)||w.s("~="+f,"(?:^|\\s+)"+p(f)+"(?:\\s+|$)",1));case "|=":return e.match(w.g("|="+f)||w.s("|="+f,"^"+p(f)+"(-|$)",1))}return 0}function v(a,e){var f=[],b=[],r,h,g,d,m,s=e,n=C.g(a)||C.s(a,a.split(I)),l=a.match(J);if(!n.length)return f;h=(n=n.slice(0)).pop();
n.length&&(r=n[n.length-1].match(K))&&(s=y(e,r[1]));if(!s)return f;d=x(h);g=s!==e&&9!==s.nodeType&&l&&/^[+~]$/.test(l[l.length-1])?function(a){for(;s=s.nextSibling;)1==s.nodeType&&(d[1]?d[1]==s.tagName.toLowerCase():1)&&(a[a.length]=s);return a}([]):s.getElementsByTagName(d[1]||"*");r=0;for(h=g.length;r<h;r++)if(m=t.apply(g[r],d))f[f.length]=m;if(!n.length)return f;k(f,function(a){c(a,n,l)&&(b[b.length]=a)});return b}function c(a,e,f,c){function b(a,c,d){for(;d=S[f[c]](d,a);)if(r(d)&&t.apply(d,x(e[c])))if(c){if(h=
b(d,c-1,d))return h}else return d}var h;return(h=b(a,e.length-1,a))&&(!c||A(h,c))}function r(a,e){return a&&"object"===typeof a&&(e=a.nodeType)&&(1==e||9==e)}function h(a){var e=[],f,c;f=0;a:for(;f<a.length;++f){for(c=0;c<e.length;++c)if(e[c]==a[f])continue a;e[e.length]=a[f]}return e}function s(a){return"object"===typeof a&&isFinite(a.length)}function y(a,e,f){return 9===a.nodeType?a.getElementById(e):a.ownerDocument&&((f=a.ownerDocument.getElementById(e))&&A(f,a)&&f||!A(a,a.ownerDocument)&&E('[id="'+
e+'"]',a)[0])}function m(a,e){var f,c,h;h=e?"string"==typeof e?m(e)[0]:!e.nodeType&&s(e)?e[0]:e:z;if(!h||!a)return[];if(a===window||r(a))return!e||a!==window&&r(h)&&A(a,h)?[a]:[];if(a&&s(a))return b(a);if(f=a.match(T)){if(f[1])return(c=y(h,f[1]))?[c]:[];if(f[2])return g(h.getElementsByTagName(f[2]));if(U&&f[3])return g(h.getElementsByClassName(f[3]))}return E(a,h)}function n(a,e){return function(f){var c,b;L.test(f)?9!==a.nodeType&&((b=c=a.getAttribute("id"))||a.setAttribute("id",b="__qwerymeupscotty"),
e(a.parentNode||a,'[id="'+b+'"]'+f,!0),c||a.removeAttribute("id")):f.length&&e(a,f,!1)}}var z=document,D=z.documentElement,E,O=/#([\w\-]+)/,P=/\.[\w\-]+/g,K=/^#([\w\-]+)$/,V=/^([\w]+)?\.([\w\-]+)$/,L=/(^|,)\s*[>~+]/,W=/^\s+|\s*([,\s\+\~>]|$)\s*/g,B=/[\s\>\+\~]/,M=/(?![\s\w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^'"]*\]|[\s\w\+\-]*\))/,R=/([.*+?\^=!:${}()|\[\]\/\\])/g,T=new RegExp(K.source+"|"+/^([\w\-]+)$/.source+"|"+/^\.([\w\-]+)$/.source),J=new RegExp("("+B.source+")"+M.source,"g"),I=new RegExp(B.source+
M.source),N=new RegExp(/^(\*|[a-z0-9]+)?(?:([\.\#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*\~]?\=)['"]?([ \w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?([^()]+)['"]?\))?/.source+")?"),S={" ":function(a){return a&&a!==D&&a.parentNode},">":function(a,e){return a&&a.parentNode==e.parentNode&&a.parentNode},"~":function(a){return a&&a.previousSibling},"+":function(a,e,f,c){return a?(f=d(a))&&(c=d(e))&&f==c&&f:!1}};l.prototype={g:function(a){return this.c[a]||
void 0},s:function(a,e,f){e=f?new RegExp(e):e;return this.c[a]=e}};var G=new l,H=new l,w=new l,C=new l,A="compareDocumentPosition"in D?function(a,e){return 16==(e.compareDocumentPosition(a)&16)}:"contains"in D?function(a,e){e=9===e.nodeType||e==window?D:e;return e!==a&&e.contains(a)}:function(a,e){for(;a=a.parentNode;)if(a===e)return 1;return 0},Q=function(){var a=z.createElement("p");return(a.innerHTML='<a href="#x">x</a>',"#x"!=a.firstChild.getAttribute("href"))?function(a,f){return"class"===f?
a.className:"href"===f||"src"===f?a.getAttribute(f,2):a.getAttribute(f)}:function(a,f){return a.getAttribute(f)}}(),U=!!z.getElementsByClassName,X=z.querySelector&&z.querySelectorAll,Y=function(a,e){var f=[],c,b;try{if(9===e.nodeType||!L.test(a))return g(e.querySelectorAll(a));k(c=a.split(","),n(e,function(a,e){b=a.querySelectorAll(e);1==b.length?f[f.length]=b.item(0):b.length&&(f=f.concat(g(b)))}));return 1<c.length&&1<f.length?h(f):f}catch(r){}return F(a,e)},F=function(a,e){var f=[],c,b,r,d;a=a.replace(W,
"$1");if(c=a.match(V)){d=u(c[2]);c=e.getElementsByTagName(c[1]||"*");b=0;for(r=c.length;b<r;b++)d.test(c[b].className)&&(f[f.length]=c[b]);return f}k(c=a.split(","),n(e,function(a,c,h){d=v(c,a);b=0;for(r=d.length;b<r;b++)if(9===a.nodeType||h||A(d[b],e))f[f.length]=d[b]}));return 1<c.length&&1<f.length?h(f):f},B=function(a){"undefined"!==typeof a.useNativeQSA&&(E=a.useNativeQSA?X?Y:F:F)};B({useNativeQSA:!0});m.configure=B;m.uniq=h;m.is=function(a,e,f){if(r(e))return a==e;if(s(e))return!!~b(e).indexOf(a);
for(var h=e.split(","),d;e=h.pop();)if(d=C.g(e)||C.s(e,e.split(I)),e=e.match(J),d=d.slice(0),t.apply(a,x(d.pop()))&&(!d.length||c(a,d,e,f)))return!0;return!1};m.pseudos={};return m});
(function(){function l(c,b,h){var d;x||(x=window[ensightenOptions.ns].qwery);d=x;if((d=d.call(h,b,h))&&0<d.length){if("_root"==b)c=h;else if(c===h)c=void 0;else{b:{for(var g=d.length,m=0;m<g;m++)if(c===d[m]){d=!0;break b}d=!1}d||(c.parentNode?(t++,c=l(c.parentNode,b,h)):c=void 0)}return c}return!1}function u(c,b,d,g){q[c.id]||(q[c.id]={});q[c.id][b]||(q[c.id][b]={});q[c.id][b][d]||(q[c.id][b][d]=[]);q[c.id][b][d].push(g)}function k(c,b,d,g){if(g||d)if(g)for(var k=0;k<q[c.id][b][d].length;k++){if(q[c.id][b][d][k]===
g){q[c.id][b][d].pop(k,1);break}}else delete q[c.id][b][d];else q[c.id][b]={}}function b(c,b,h){if(q[c][h]){var g=b.target||b.srcElement,k,m,n={},p=m=0;t=0;for(k in q[c][h])q[c][h].hasOwnProperty(k)&&(m=l(g,k,v[c].element))&&d.matchesEvent(h,v[c].element,m,"_root"==k,b)&&(t++,q[c][h][k].match=m,n[t]=q[c][h][k]);b.stopPropagation=function(){b.cancelBubble=!0};for(m=0;m<=t;m++)if(n[m])for(p=0;p<n[m].length;p++){if(!1===n[m][p].call(n[m].match,b)){d.cancel(b);return}if(b.cancelBubble)return}}}function g(c,
g,h,l){function p(c){return function(d){b(m,d,c)}}c instanceof Array||(c=[c]);h||"function"!=typeof g||(h=g,g="_root");var m=this.id,n;for(n=0;n<c.length;n++)q[m]&&q[m][c[n]]||d.addEvent(this,c[n],p(c[n])),l?k(this,c[n],g,h):u(this,c[n],g,h);return this}function d(b,g,h,k){if("string"==typeof b&&"function"==typeof g||"string"==typeof g)d(document).on(b,g,h,k||!1);if(!(this instanceof d)){for(var l in v)if(v[l].element===b)return v[l];p++;v[p]=new d(b,p);v[p]._on=v[p].on;v[p].on=function(b,c,d,g){var h=
"function"==typeof c?c:d;if("function"==typeof c?d:g)b=[b],"string"==typeof c&&b.push(c),b.push(function(b){return function(c){c.defaultPrevented||window[ensightenOptions.ns].Delegate.load(this);if(this.nodeName&&"a"!=this.nodeName.toLowerCase())return b.call(this);"undefined"!=typeof c.preventDefault?c.preventDefault():c.returnValue=!1;b.call(this)}}(h)),this._on.apply(this,b);else return this._on.call(this,b,c,d)};return v[p]}this.element=b;this.id=g}var x,t=0,p=0,q={},v={};d.prototype.on=function(b,
d,h){return g.call(this,b,d,h)};d.prototype.off=function(b,d,h){return g.call(this,b,d,h,!0)};d.cancel=function(b){b.preventDefault();b.stopPropagation()};d.addEvent=function(b,d,g){b.element.addEventListener(d,g,"blur"==d||"focus"==d)};d.matchesEvent=function(){return!0};d.load=function(b){setTimeout(function(b,c){return function(){if(b.nodeName&&"a"==b.nodeName.toLowerCase()){if(c&&/^javascript\s*\:/.test(c))return(new Function(unescape(c))).call(window);c&&(window.location.href=c)}}}(b,b.href||
""),750)};window[ensightenOptions.ns].Delegate=d})();(function(l){var u=l.addEvent;l.addEvent=function(k,b,g){if(k.element.addEventListener)return u(k,b,g);"focus"==b&&(b="focusin");"blur"==b&&(b="focusout");k.element.attachEvent("on"+b,g)};l.cancel=function(k){k.preventDefault&&k.preventDefault();k.stopPropagation&&k.stopPropagation();k.returnValue=!1;k.cancelBubble=!0}})(window[ensightenOptions.ns].Delegate);window[ensightenOptions.ns].on=window[ensightenOptions.ns].Delegate;
Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;try{var arr_microsites={"jJRSMARKETING_Thankyou-Preferred-credit-card":true,"jJRSMARKETING_Thankyou-Premier-credit-card":true,"jJRSMARKETING_Thankyou-Prestige-credit-card":true,"jJRSMARKETING_DoubleCash":true,"jJRSMARKETING_Compare-Thankyou-credit-cards":true,"jJRSMARKETING_citi-apple-pay":true};var arr_postLogin={"jcbol_pnt_crecarpay_Input":false,"jcbol_pnt_schpayhis_showResult":false,
"jcbol_pnt_adddra_Input":false,"jcbol_pnt_seedrw_Input":false,"jcbol_pnt_crecardirdeblan_landing":false,"jcbol_pnt_crecardirdebset_input":false,"jcbol_common_Dashboard":false,"jjba_tfr_common_100":true,"j7_120":true,"j7_700":true,"jUSCBOL_NCManageAuthUser":true,"jUSCBOL_CManageAuthUser":true,"jEDelivery_PlessWizard":true,"j23_257":true};var arr_banking={"jJSOSIGNON_SignOffAdOverlay":true,"jJRSPRODSERV_ProdServDetail":false,"jcbol_common_PaymentNTransfers":true,"jUSCBOL_Loginpage_Cookied":true,"jUSCBOL_Loginpage_Uncookied":true,
"jcbol_common_ADA":true,"jJRSPRODSERV_ProdServDetail":true,"jUSCBOL_Loginpage_Citigold":true};var arr_banking_ids=["Checking","Citigold","ChkCBA","ChkBasicChecking","accessAccount","AOProductSelection"];var arr_cardPages={"jJRSMARKETING_CitiHome":true,"jJRSMARKETING_view-all-credit-cards":true,"jJRSMARKETING_most-popular-credit-cards":true,"jJRSMARKETING_balance-transfer-credit-cards":true,"jJRSMARKETING_reward-credit-cards":true,"jJRSMARKETING_savings-and-cash-back-credit-cards":true,"jJRSMARKETING_all-small-business-credit-cards":true,
"jJRSMARKETING_all-student-credit-cards":true,"jJRSMARKETING_travel-reward-credit-cards":true,"jJRSMARKETING_american-airlines-aadvantage-credit-cards":true,"jJRSMARKETING_thank-you-rewards-credit-cards":true,"jJRSMARKETING_visa-credit-cards":true,"jJRSMARKETING_mastercard-credit-cards":true,"jJRSMARKETING_Citi-costco-anywhere-visa-credit-card":true,"jJRSMARKETING_Citi-costco-anywhere-visa-business-credit-card":true,"jJRSMARKETING_citi-aadvantage-platinum-select-credit-card":true,"jJRSMARKETING_citi-aadvantage-gold-credit-card":true,
"jJRSMARKETING_citibusiness-aadvantage-platinum-select-credit-card":true,"jJRSMARKETING_citi-aadvantage-executive-credit-card":true,"jJRSMARKETING_citi-diamond-preferred-credit-card":true,"jJRSMARKETING_citi-double-cash-credit-card":true,"jJRSMARKETING_expedia-plus":true,"jJRSMARKETING_expedia-plus-voyager":true,"jJRSMARKETING_hilton-hhonors-visa-signature-card":true,"jJRSMARKETING_hilton-hhonors-reserve-card":true,"jJRSMARKETING_citi-simplicity-credit-card":true,"jJRSMARKETING_citi-thankyou-credit-card-preferred-card":true,
"jJRSMARKETING_citi-thankyou-premier-credit-card":true,"jJRSMARKETING_citi-prestige-card":true,"jJRSMARKETING_citi-thankyou-preferred-credit-cards-for-college-students":true,"jJRSMARKETING_citi-att-access-credit-card":true,"jJRSMARKETING_citi-att-access-more-credit-card":true,"jJRSMARKETING_citi-secured-credit-card":true,"jJRSMARKETING_low-interest-credit-card":true};var arr_acquisition={"jJRSACQ_Application_Default":false,"jJRSACQ_Application_AA":false,"jJRSACQ_Application_BizAA":false,"jJRSACQ_Application_Costco":false,
"jJRSACQ_Application_Costco_Biz":false,"jJRSACQ_Application_Hilton":false,"jJRSACQ_Application_TY":false,"jJRSACQ_Application_college":false,"jJRSACQ_Application_Secured":false,"jJRSACQ_Approval_Default":false,"jJRSACQ_Pending_Default":false,"jJRSACQ_Declined_Default":false,"jJRSACQ_Processing_Default":false,"jJRSACQ_Invitation":false,"jJRSAO_MUSSNEntry":false,"jJRSAO_IAOProfile":false,"jJRSACQ_AboutYou_Default":false,"JRSACQ_AccountDetails_Approval_Default":false,"jJRSACQ_AccountDetails_Pending_Default":false,
"jJRSACQ_AccountDetails_Declined_Default":false};var arr_sapient={"Sapient_cbol_balance_build":true,"Sapient_cbol_16_savings_Q4_10X-interest-offer":true,"Sapient_cbol_16_checking_aquisition_400-offer":true,"Sapient_citi_benefit_home_landing":true};var currentPageDef_tnt="";var addMbox_tnt=false;if(typeof window.citiData!="undefined"&&typeof window.citiData.globalInfo!="undefined"&&typeof window.citiData.globalInfo.pageDef!="undefined")currentPageDef_tnt=window.citiData.globalInfo.pageDef;else if(typeof window.citiData!=
"undefined"&&typeof window.citiData.pageDef!="undefined")currentPageDef_tnt=window.citiData.pageDef;else if(typeof window._citiData!="undefined"&&typeof window._citiData.pageDef!="undefined")currentPageDef_tnt=window._citiData.pageDef;else if(typeof window.pageDef!="undefined")currentPageDef_tnt=window.pageDef;function tntGetCookie(c,notFoundString){var dc=document.cookie;if(dc.indexOf(c)!=-1){var cs=dc.split(c)[1];return(cs.substr(0,1)=="\x3d"?cs.substr(1):cs).split(";")[0]}return notFoundString||
""}function positionCookie(strCookie,position,notFoundString){strCookie=strCookie.split("-");if(typeof strCookie[position-1]!=="undefined")return strCookie[position-1];return notFoundString||""}function isID_tnt(){var name="ID\x3d";var query=window.location.href.toString();var ca1=query.split(name);if(ca1.length>1){var ca=ca1[1].split("\x26");if(arr_banking_ids.indexOf(ca[0])>=0)return true}return false}if(typeof arr_sapient[currentPageDef_tnt]!="undefined"||typeof arr_acquisition[currentPageDef_tnt]!=
"undefined"||typeof arr_microsites[currentPageDef_tnt]!="undefined"||typeof arr_cardPages[currentPageDef_tnt]!="undefined"||typeof arr_banking[currentPageDef_tnt]!="undefined"||typeof arr_postLogin[currentPageDef_tnt]!="undefined"){addMbox_tnt=true;if(currentPageDef_tnt=="jJRSPRODSERV_ProdServDetail"&&!isID_tnt())addMbox_tnt=false}if(addMbox_tnt){window.targetPageParams=function(){var tnt_params="pageDef\x3d"+currentPageDef_tnt;if(typeof arr_cardPages[currentPageDef_tnt]!="undefined"){var categoryID_tnt=
"";var campaignID_tnt="";var tnt_ECM="";if(typeof window.citiData!="undefined"&&typeof window.citiData.generalInfo!="undefined"&&typeof window.citiData.generalInfo.isECM!="undefined")tnt_ECM="\x26isECM\x3d"+window.citiData.generalInfo.isECM;if(typeof window.bk_results!="undefined"&&typeof window.bk_results.campaigns!="undefined"&&window.bk_results.campaigns.length>0)if(typeof window.bk_results.campaigns[0].campaign!="undefined"&&typeof window.bk_results.campaigns[0].categories!="undefined"){campaignID_tnt=
"\x26bkCampaignIDs\x3d"+window.bk_results.campaigns[0].campaign;categoryID_tnt+="\x26bkCategoryIDs\x3d,";for(i=0;i<window.bk_results.campaigns[0].categories.length;i++)categoryID_tnt+=window.bk_results.campaigns[0].categories[i].categoryID+","}tnt_params+=campaignID_tnt+categoryID_tnt+tnt_ECM}if(typeof arr_acquisition[currentPageDef_tnt]!="undefined"){var cardType_tnt="";var sc_tnt="";var status_tnt="";if(typeof window.citiData!="undefined"&&typeof window.citiData.prodName!="undefined")cardType_tnt=
"\x26cardType\x3d"+window.citiData.prodName;if(typeof window.citiData!="undefined"&&typeof window.citiData.cardProdSourceCode!="undefined")sc_tnt="\x26sourceCode\x3d"+window.citiData.cardProdSourceCode;if(typeof window.citiData!="undefined"&&typeof window.citiData.cardAppStatus!="undefined")status_tnt="\x26appStatus\x3d"+window.citiData.cardAppStatus;tnt_params+=cardType_tnt+sc_tnt+status_tnt}if(currentPageDef_tnt==="jUSCBOL_Loginpage_Cookied"||currentPageDef_tnt==="jUSCBOL_Loginpage_Uncookied"||
currentPageDef_tnt==="jUSCBOL_Loginpage_Citigold"){if(!tntGetCookie("CBOLECM",false))tnt_params+="\x26ProspectCustomer\x3dtrue";else{if(tntGetCookie("username")!="")tnt_params+="\x26cookiedUID\x3dYES";if(positionCookie(tntGetCookie("CBOLECM"),20,false)==="Y")tnt_params+="\x26BlueCustomer\x3dtrue";if(positionCookie(tntGetCookie("CBOLECM"),10,false).trim()!==""){tnt_params+="\x26cards_cc\x3d"+positionCookie(tntGetCookie("CBOLECM"),10,false).split("|").length;tnt_params+="\x26PID\x3d"+positionCookie(tntGetCookie("CBOLECM"),
10,false)}if(positionCookie(tntGetCookie("CBOLECM"),10,false).split("|").length>=1&&positionCookie(tntGetCookie("CBOLECM"),14,false)=="Y")tnt_params+="\x26MRC\x3dYES"}if(typeof citiData!="undefined"&&typeof citiData.pageLanguage!="undefined")tnt_params+="\x26pageLanguage\x3d"+citiData.pageLanguage}if(typeof arr_banking[currentPageDef_tnt]!="undefined"&&!arr_banking[currentPageDef_tnt]||typeof arr_postLogin[currentPageDef_tnt]!="undefined"&&!arr_postLogin[currentPageDef_tnt])tnt_params+="\x26UniquePageDef\x3dfalse";
return tnt_params};var mboxCopyright="Copyright 1996-2014. Adobe Systems Incorporated. All rights reserved.";var TNT=TNT||{};TNT.a=TNT.a||{};TNT.a.nestedMboxes=[];TNT.a.isDomLoaded=false;TNT.getGlobalMboxName=function(){return"target-global-mbox"};TNT.getGlobalMboxLocation=function(){return""};TNT.isAutoCreateGlobalMbox=function(){return true};TNT.getClientMboxExtraParameters=function(){return""};TNT.a.b=function(){var c={}.toString;var d=window.targetPageParams;var e=null;if(typeof d==="undefined"||
c.call(d)!=="[object Function]")return[];try{e=d()}catch(f){}if(e===null)return[];if(c.call(e)==="[object Array]")return e;if(c.call(e)==="[object String]"&&e.length>0){var g=e.trim().split("\x26");for(var h=0;h<g.length;h++){if(g[h].indexOf("\x3d")<=0){g.splice(h,1);continue}g[h]=decodeURIComponent(g[h])}return g}if(c.call(e)==="[object Object]")return TNT.a.i([],e);return[]};TNT.a.i=function(j,k){var l=[];var m=j.join(".");var n=undefined;for(o in k){if(!k.hasOwnProperty(o))continue;n=k[o];if(typeof n===
"object"){j.push(o);var p=TNT.a.i(j,n);j.pop();for(var h=0;h<p.length;h++)l.push(p[h]);continue}l.push((m.length>0?m+".":"")+o+"\x3d"+n)}return l};mboxUrlBuilder=function(q,r){this.q=q;this.r=r;this.s=new Array;this.t=function(u){return u};this.v=null};mboxUrlBuilder.prototype.addNewParameter=function(w,x){this.s.push({name:w,value:x});return this};mboxUrlBuilder.prototype.addParameterIfAbsent=function(w,x){if(x){for(var y=0;y<this.s.length;y++){var z=this.s[y];if(z.name===w)return this}this.checkInvalidCharacters(w);
return this.addNewParameter(w,x)}};mboxUrlBuilder.prototype.addParameter=function(w,x){this.checkInvalidCharacters(w);for(var y=0;y<this.s.length;y++){var z=this.s[y];if(z.name===w){z.value=x;return this}}return this.addNewParameter(w,x)};mboxUrlBuilder.prototype.addParameters=function(s){if(!s)return this;for(var y=0;y<s.length;y++){var A=s[y].indexOf("\x3d");if(A==-1||A==0)continue;this.addParameter(s[y].substring(0,A),s[y].substring(A+1,s[y].length))}return this};mboxUrlBuilder.prototype.setServerType=
function(B){this.C=B};mboxUrlBuilder.prototype.setBasePath=function(v){this.v=v};mboxUrlBuilder.prototype.setUrlProcessAction=function(D){this.t=D};mboxUrlBuilder.prototype.buildUrl=function(){var E=this.v?this.v:"/m2/"+this.r+"/mbox/"+this.C;var F=document.location.protocol=="file:"?"http:":document.location.protocol;var u=F+"//"+this.q+E;var G=u.indexOf("?")!=-1?"\x26":"?";for(var y=0;y<this.s.length;y++){var z=this.s[y];u+=G+encodeURIComponent(z.name)+"\x3d"+encodeURIComponent(z.value);G="\x26"}return this.H(this.t(u))};
mboxUrlBuilder.prototype.getParameters=function(){return this.s};mboxUrlBuilder.prototype.setParameters=function(s){this.s=s};mboxUrlBuilder.prototype.clone=function(){var I=new mboxUrlBuilder(this.q,this.r);I.setServerType(this.C);I.setBasePath(this.v);I.setUrlProcessAction(this.t);for(var y=0;y<this.s.length;y++)I.addParameter(this.s[y].name,this.s[y].value);return I};mboxUrlBuilder.prototype.H=function(J){return J.replace(/\"/g,"\x26quot;").replace(/>/g,"\x26gt;")};mboxUrlBuilder.prototype.checkInvalidCharacters=
function(w){var K=new RegExp("('|\")");if(K.exec(w))throw"Parameter '"+w+"' contains invalid characters";};mboxStandardFetcher=function(){};mboxStandardFetcher.prototype.getType=function(){return"standard"};mboxStandardFetcher.prototype.fetch=function(L){L.setServerType(this.getType());document.write("\x3c"+"scr"+'ipt src\x3d"'+L.buildUrl()+'" language\x3d"JavaScript"\x3e\x3c'+"/scr"+"ipt\x3e")};mboxStandardFetcher.prototype.cancel=function(){};mboxAjaxFetcher=function(){};mboxAjaxFetcher.prototype.getType=
function(){return"ajax"};mboxAjaxFetcher.prototype.fetch=function(L){L.setServerType(this.getType());var u=L.buildUrl();this.M=document.createElement("script");this.M.src=u;document.body.appendChild(this.M)};mboxAjaxFetcher.prototype.cancel=function(){};mboxMap=function(){this.N=new Object;this.O=new Array};mboxMap.prototype.put=function(P,x){if(!this.N[P])this.O[this.O.length]=P;this.N[P]=x};mboxMap.prototype.get=function(P){return this.N[P]};mboxMap.prototype.remove=function(P){this.N[P]=undefined;
var Q=[];for(var i=0;i<this.O.length;i++)if(this.O[i]!==P)Q.push(this.O[i]);this.O=Q};mboxMap.prototype.each=function(D){for(var y=0;y<this.O.length;y++){var P=this.O[y];var x=this.N[P];if(x){var l=D(P,x);if(l===false)break}}};mboxMap.prototype.isEmpty=function(){return this.O.length===0};mboxFactory=function(R,r,S){this.T=false;this.R=R;this.S=S;this.U=new mboxList;mboxFactories.put(S,this);this.V=typeof document.createElement("div").replaceChild!="undefined"&&function(){return true}()&&typeof document.getElementById!=
"undefined"&&typeof(window.attachEvent||document.addEventListener||window.addEventListener)!="undefined"&&typeof encodeURIComponent!="undefined";this.W=this.V&&mboxGetPageParameter("mboxDisable")==null;var X=S=="default";this.Y=new mboxCookieManager("mbox"+(X?"":"-"+S),function(){return mboxCookiePageDomain()}());this.W=this.W&&this.Y.getCookie("disable")==null;if(this.isAdmin())this.enable();this.Z();this._=mboxGenerateId();this.ab=mboxScreenHeight();this.bb=mboxScreenWidth();this.cb=mboxBrowserWidth();
this.db=mboxBrowserHeight();this.eb=mboxScreenColorDepth();this.fb=mboxBrowserTimeOffset();this.gb=new mboxSession(this._,"mboxSession","session",31*60,this.Y);this.hb=new mboxPC("PC",1209600,this.Y);this.L=new mboxUrlBuilder(R,r);this.ib(this.L,X);this.jb=(new Date).getTime();this.kb=this.jb;var lb=this;this.addOnLoad(function(){lb.kb=(new Date).getTime()});if(this.V){this.addOnLoad(function(){lb.T=true;lb.getMboxes().each(function(mb){mb.nb();mb.setFetcher(new mboxAjaxFetcher);mb.finalize()});TNT.a.nestedMboxes=
[];TNT.a.isDomLoaded=true});if(this.W){this.limitTraffic(100,10368E3);this.ob();this.pb=new mboxSignaler(function(qb,s){return lb.create(qb,s)},this.Y)}}};mboxFactory.prototype.isEnabled=function(){return this.W};mboxFactory.prototype.getDisableReason=function(){return this.Y.getCookie("disable")};mboxFactory.prototype.isSupported=function(){return this.V};mboxFactory.prototype.disable=function(rb,sb){if(typeof rb=="undefined")rb=60*60;if(typeof sb=="undefined")sb="unspecified";if(!this.isAdmin()){this.W=
false;this.Y.setCookie("disable",sb,rb)}};mboxFactory.prototype.enable=function(){this.W=true;this.Y.deleteCookie("disable")};mboxFactory.prototype.isAdmin=function(){return document.location.href.indexOf("mboxEnv")!=-1};mboxFactory.prototype.limitTraffic=function(tb,rb){};mboxFactory.prototype.addOnLoad=function(ub){if(this.isDomLoaded())ub();else{var vb=false;var wb=function(){if(vb)return;vb=true;ub()};this.xb.push(wb);if(this.isDomLoaded()&&!vb)wb()}};mboxFactory.prototype.getEllapsedTime=function(){return this.kb-
this.jb};mboxFactory.prototype.getEllapsedTimeUntil=function(yb){return yb-this.jb};mboxFactory.prototype.getMboxes=function(){return this.U};mboxFactory.prototype.get=function(qb,zb){return this.U.get(qb).getById(zb||0)};mboxFactory.prototype.update=function(qb,s){if(!this.isEnabled())return;if(!this.isDomLoaded()){var lb=this;this.addOnLoad(function(){lb.update(qb,s)});return}if(this.U.get(qb).length()==0)throw"Mbox "+qb+" is not defined";this.U.get(qb).each(function(mb){mb.getUrlBuilder().addParameter("mboxPage",
mboxGenerateId());mboxFactoryDefault.setVisitorIdParameters(mb.getUrlBuilder(),qb);mb.load(s)})};mboxFactory.prototype.setVisitorIdParameters=function(u,qb){var imsOrgId="61834D9B5228A7430A490D45@AdobeOrg";if(typeof Visitor=="undefined"||imsOrgId.length==0)return;var visitor=Visitor.getInstance(imsOrgId);if(visitor.isAllowed()){var addVisitorValueToUrl=function(param,getter,mboxName){if(visitor[getter]){var callback=function(value){if(value)u.addParameter(param,value)};var value;if(typeof mboxName!=
"undefined")value=visitor[getter]("mbox:"+mboxName);else value=visitor[getter](callback);callback(value)}};addVisitorValueToUrl("mboxMCGVID","getMarketingCloudVisitorID");addVisitorValueToUrl("mboxMCGLH","getAudienceManagerLocationHint");addVisitorValueToUrl("mboxAAMB","getAudienceManagerBlob");addVisitorValueToUrl("mboxMCAVID","getAnalyticsVisitorID");addVisitorValueToUrl("mboxMCSDID","getSupplementalDataID",qb)}};mboxFactory.prototype.create=function(qb,s,Ab){if(!this.isSupported())return null;
var u=this.L.clone();u.addParameter("mboxCount",this.U.length()+1);u.addParameters(s);this.setVisitorIdParameters(u,qb);var zb=this.U.get(qb).length();var Bb=this.S+"-"+qb+"-"+zb;var Cb;if(Ab)Cb=new mboxLocatorNode(Ab);else{if(this.T)throw"The page has already been loaded, can't write marker";Cb=new mboxLocatorDefault(Bb)}try{var lb=this;var Db="mboxImported-"+Bb;var mb=new mbox(qb,zb,u,Cb,Db);if(this.W)mb.setFetcher(this.T?new mboxAjaxFetcher:new mboxStandardFetcher);mb.setOnError(function(Eb,B){mb.setMessage(Eb);
mb.activate();if(!mb.isActivated()){lb.disable(60*60,Eb);window.location.reload(false)}});this.U.add(mb)}catch(Fb){this.disable();throw'Failed creating mbox "'+qb+'", the error was: '+Fb;}var Gb=new Date;u.addParameter("mboxTime",Gb.getTime()-Gb.getTimezoneOffset()*6E4);return mb};mboxFactory.prototype.getCookieManager=function(){return this.Y};mboxFactory.prototype.getPageId=function(){return this._};mboxFactory.prototype.getPCId=function(){return this.hb};mboxFactory.prototype.getSessionId=function(){return this.gb};
mboxFactory.prototype.getSignaler=function(){return this.pb};mboxFactory.prototype.getUrlBuilder=function(){return this.L};mboxFactory.prototype.ib=function(u,X){u.addParameter("mboxHost",document.location.hostname).addParameter("mboxSession",this.gb.getId());if(!X)u.addParameter("mboxFactoryId",this.S);if(this.hb.getId()!=null)u.addParameter("mboxPC",this.hb.getId());u.addParameter("mboxPage",this._);u.addParameter("screenHeight",this.ab);u.addParameter("screenWidth",this.bb);u.addParameter("browserWidth",
this.cb);u.addParameter("browserHeight",this.db);u.addParameter("browserTimeOffset",this.fb);u.addParameter("colorDepth",this.eb);u.addParameter("mboxXDomain","x-only");u.setUrlProcessAction(function(u){u+="\x26mboxURL\x3d"+encodeURIComponent(document.location);var Hb=encodeURIComponent(document.referrer);if(u.length+Hb.length<2E3)u+="\x26mboxReferrer\x3d"+Hb;u+="\x26mboxVersion\x3d"+mboxVersion;return u})};mboxFactory.prototype.Ib=function(){return""};mboxFactory.prototype.ob=function(){document.write("\x3cstyle\x3e."+
"mboxDefault"+" { visibility:hidden; }\x3c/style\x3e")};mboxFactory.prototype.isDomLoaded=function(){return this.T};mboxFactory.prototype.Z=function(){if(this.xb!=null)return;this.xb=new Array;var lb=this;(function(){var Jb=document.addEventListener?"DOMContentLoaded":"onreadystatechange";var Kb=false;var Lb=function(){if(Kb)return;Kb=true;for(var i=0;i<lb.xb.length;++i)lb.xb[i]()};if(document.addEventListener){document.addEventListener(Jb,function(){document.removeEventListener(Jb,arguments.callee,
false);Lb()},false);window.addEventListener("load",function(){document.removeEventListener("load",arguments.callee,false);Lb()},false)}else if(document.attachEvent)if(self!==self.top)document.attachEvent(Jb,function(){if(document.readyState==="complete"){document.detachEvent(Jb,arguments.callee);Lb()}});else{var Mb=function(){try{document.documentElement.doScroll("left");Lb()}catch(Nb){setTimeout(Mb,13)}};Mb()}if(document.readyState==="complete")Lb()})()};mboxSignaler=function(Ob,Y){this.Y=Y;var Pb=
Y.getCookieNames("signal-");for(var y=0;y<Pb.length;y++){var Qb=Pb[y];var Rb=Y.getCookie(Qb).split("\x26");var mb=Ob(Rb[0],Rb);mb.load();Y.deleteCookie(Qb)}};mboxSignaler.prototype.signal=function(Sb,qb){this.Y.setCookie("signal-"+Sb,mboxShiftArray(arguments).join("\x26"),45*60)};mboxList=function(){this.U=new Array};mboxList.prototype.add=function(mb){if(mb!=null)this.U[this.U.length]=mb};mboxList.prototype.get=function(qb){var l=new mboxList;for(var y=0;y<this.U.length;y++){var mb=this.U[y];if(mb.getName()==
qb)l.add(mb)}return l};mboxList.prototype.getById=function(h){return this.U[h]};mboxList.prototype.length=function(){return this.U.length};mboxList.prototype.each=function(D){if(typeof D!=="function")throw"Action must be a function, was: "+typeof D;for(var y=0;y<this.U.length;y++)D(this.U[y])};mboxLocatorDefault=function(w){this.w="mboxMarker-"+w;document.write('\x3cdiv id\x3d"'+this.w+'" style\x3d"visibility:hidden;display:none"\x3e\x26nbsp;\x3c/div\x3e')};mboxLocatorDefault.prototype.locate=function(){var Tb=
document.getElementById(this.w);while(Tb!=null){if(Tb.nodeType==1)if(Tb.className=="mboxDefault")return Tb;Tb=Tb.previousSibling}return null};mboxLocatorDefault.prototype.force=function(){var Ub=document.createElement("div");Ub.className="mboxDefault";var Vb=document.getElementById(this.w);if(Vb)Vb.parentNode.insertBefore(Ub,Vb);return Ub};mboxLocatorNode=function(Wb){this.Tb=Wb};mboxLocatorNode.prototype.locate=function(){return typeof this.Tb=="string"?document.getElementById(this.Tb):this.Tb};
mboxLocatorNode.prototype.force=function(){return null};mboxCreate=function(qb){var mb=mboxFactoryDefault.create(qb,mboxShiftArray(arguments));if(mb)mb.load();return mb};mboxDefine=function(Ab,qb){var mb=mboxFactoryDefault.create(qb,mboxShiftArray(mboxShiftArray(arguments)),Ab);return mb};mboxUpdate=function(qb){mboxFactoryDefault.update(qb,mboxShiftArray(arguments))};mbox=function(w,Xb,L,Yb,Db){this.Zb=null;this._b=0;this.Cb=Yb;this.Db=Db;this.ac=null;this.bc=new mboxOfferContent;this.Ub=null;this.L=
L;this.message="";this.cc=new Object;this.dc=0;this.Xb=Xb;this.w=w;this.ec();L.addParameter("mbox",w).addParameter("mboxId",Xb);this.fc=function(){};this.gc=function(){};this.hc=null;this.ic=document.documentMode>=10&&!TNT.a.isDomLoaded;if(this.ic){this.jc=TNT.a.nestedMboxes;this.jc.push(this.w)}};mbox.prototype.getId=function(){return this.Xb};mbox.prototype.ec=function(){if(this.w.length>250)throw"Mbox Name "+this.w+" exceeds max length of "+"250 characters.";else if(this.w.match(/^\s+|\s+$/g))throw"Mbox Name "+
this.w+" has leading/trailing whitespace(s).";};mbox.prototype.getName=function(){return this.w};mbox.prototype.getParameters=function(){var s=this.L.getParameters();var l=new Array;for(var y=0;y<s.length;y++)if(s[y].name.indexOf("mbox")!=0)l[l.length]=s[y].name+"\x3d"+s[y].value;return l};mbox.prototype.setOnLoad=function(D){this.gc=D;return this};mbox.prototype.setMessage=function(Eb){this.message=Eb;return this};mbox.prototype.setOnError=function(fc){this.fc=fc;return this};mbox.prototype.setFetcher=
function(kc){if(this.ac)this.ac.cancel();this.ac=kc;return this};mbox.prototype.getFetcher=function(){return this.ac};mbox.prototype.load=function(s){if(this.ac==null)return this;this.setEventTime("load.start");this.cancelTimeout();this._b=0;var L=s&&s.length>0?this.L.clone().addParameters(s):this.L;this.ac.fetch(L);var lb=this;this.lc=setTimeout(function(){lb.fc("browser timeout",lb.ac.getType())},15E3);this.setEventTime("load.end");return this};mbox.prototype.loaded=function(){this.cancelTimeout();
if(!this.activate()){var lb=this;setTimeout(function(){lb.loaded()},100)}};mbox.prototype.activate=function(){if(this._b)return this._b;this.setEventTime("activate"+ ++this.dc+".start");if(this.ic&&this.jc[this.jc.length-1]!==this.w)return this._b;if(this.show()){this.cancelTimeout();this._b=1}this.setEventTime("activate"+this.dc+".end");if(this.ic)this.jc.pop();return this._b};mbox.prototype.isActivated=function(){return this._b};mbox.prototype.setOffer=function(bc){if(bc&&bc.show&&bc.setOnLoad)this.bc=
bc;else throw"Invalid offer";return this};mbox.prototype.getOffer=function(){return this.bc};mbox.prototype.show=function(){this.setEventTime("show.start");var l=this.bc.show(this);this.setEventTime(l==1?"show.end.ok":"show.end");return l};mbox.prototype.showContent=function(mc){if(mc==null)return 0;if(this.Ub==null||!this.Ub.parentNode){this.Ub=this.getDefaultDiv();if(this.Ub==null)return 0}if(this.Ub!=mc){this.nc(this.Ub);this.Ub.parentNode.replaceChild(mc,this.Ub);this.Ub=mc}this.oc(mc);this.gc();
return 1};mbox.prototype.hide=function(){this.setEventTime("hide.start");var l=this.showContent(this.getDefaultDiv());this.setEventTime(l==1?"hide.end.ok":"hide.end.fail");return l};mbox.prototype.finalize=function(){this.setEventTime("finalize.start");this.cancelTimeout();if(this.getDefaultDiv()==null)if(this.Cb.force()!=null)this.setMessage("No default content, an empty one has been added");else this.setMessage("Unable to locate mbox");if(!this.activate()){this.hide();this.setEventTime("finalize.end.hide")}this.setEventTime("finalize.end.ok")};
mbox.prototype.cancelTimeout=function(){if(this.lc)clearTimeout(this.lc);if(this.ac!=null)this.ac.cancel()};mbox.prototype.getDiv=function(){return this.Ub};mbox.prototype.getDefaultDiv=function(){if(this.hc==null)this.hc=this.Cb.locate();return this.hc};mbox.prototype.setEventTime=function(pc){this.cc[pc]=(new Date).getTime()};mbox.prototype.getEventTimes=function(){return this.cc};mbox.prototype.getImportName=function(){return this.Db};mbox.prototype.getURL=function(){return this.L.buildUrl()};
mbox.prototype.getUrlBuilder=function(){return this.L};mbox.prototype.qc=function(Ub){return Ub.style.display!="none"};mbox.prototype.oc=function(Ub){this.rc(Ub,true)};mbox.prototype.nc=function(Ub){this.rc(Ub,false)};mbox.prototype.rc=function(Ub,sc){Ub.style.visibility=sc?"visible":"hidden";Ub.style.display=sc?"block":"none"};mbox.prototype.nb=function(){this.ic=false};mbox.prototype.relocateDefaultDiv=function(){this.hc=this.Cb.locate()};mboxOfferContent=function(){this.gc=function(){}};mboxOfferContent.prototype.show=
function(mb){var l=mb.showContent(document.getElementById(mb.getImportName()));if(l==1)this.gc();return l};mboxOfferContent.prototype.setOnLoad=function(gc){this.gc=gc};mboxOfferAjax=function(mc){this.mc=mc;this.gc=function(){}};mboxOfferAjax.prototype.setOnLoad=function(gc){this.gc=gc};mboxOfferAjax.prototype.show=function(mb){var tc=document.createElement("div");tc.id=mb.getImportName();tc.innerHTML=this.mc;var l=mb.showContent(tc);if(l==1)this.gc();return l};mboxOfferDefault=function(){this.gc=
function(){}};mboxOfferDefault.prototype.setOnLoad=function(gc){this.gc=gc};mboxOfferDefault.prototype.show=function(mb){var l=mb.hide();if(l==1)this.gc();return l};mboxCookieManager=function mboxCookieManager(w,uc){this.w=w;this.uc=uc==""||uc.indexOf(".")==-1?"":"; domain\x3d"+uc;this.vc=new mboxMap;this.loadCookies()};mboxCookieManager.prototype.isEnabled=function(){this.setCookie("check","true",60);this.loadCookies();return this.getCookie("check")=="true"};mboxCookieManager.prototype.setCookie=
function(w,x,rb){if(typeof w!="undefined"&&typeof x!="undefined"&&typeof rb!="undefined"){var wc=new Object;wc.name=w;wc.value=escape(x);wc.expireOn=Math.ceil(rb+(new Date).getTime()/1E3);this.vc.put(w,wc);this.saveCookies()}};mboxCookieManager.prototype.getCookie=function(w){var wc=this.vc.get(w);return wc?unescape(wc.value):null};mboxCookieManager.prototype.deleteCookie=function(w){this.vc.remove(w);this.saveCookies()};mboxCookieManager.prototype.getCookieNames=function(xc){var yc=new Array;this.vc.each(function(w,
wc){if(w.indexOf(xc)==0)yc[yc.length]=w});return yc};mboxCookieManager.prototype.saveCookies=function(){var zc=true;var Ac="disable";var Bc=new Array;var Cc=0;this.vc.each(function(w,wc){if(!zc||w===Ac){Bc[Bc.length]=w+"#"+wc.value+"#"+wc.expireOn;if(Cc<wc.expireOn)Cc=wc.expireOn}});var Dc=new Date(Cc*1E3);document.cookie=this.w+"\x3d"+Bc.join("|")+"; expires\x3d"+Dc.toGMTString()+"; path\x3d/"+this.uc};mboxCookieManager.prototype.loadCookies=function(){this.vc=new mboxMap;var Ec=document.cookie.indexOf(this.w+
"\x3d");if(Ec!=-1){var Fc=document.cookie.indexOf(";",Ec);if(Fc==-1){Fc=document.cookie.indexOf(",",Ec);if(Fc==-1)Fc=document.cookie.length}var Gc=document.cookie.substring(Ec+this.w.length+1,Fc).split("|");var Hc=Math.ceil((new Date).getTime()/1E3);for(var y=0;y<Gc.length;y++){var wc=Gc[y].split("#");if(Hc<=wc[2]){var Ic=new Object;Ic.name=wc[0];Ic.value=wc[1];Ic.expireOn=wc[2];this.vc.put(Ic.name,Ic)}}}};mboxSession=function(Jc,Kc,Qb,Lc,Y){this.Kc=Kc;this.Qb=Qb;this.Lc=Lc;this.Y=Y;this.Mc=false;
this.Xb=typeof mboxForceSessionId!="undefined"?mboxForceSessionId:mboxGetPageParameter(this.Kc);if(this.Xb==null||this.Xb.length==0){this.Xb=Y.getCookie(Qb);if(this.Xb==null||this.Xb.length==0){this.Xb=Jc;this.Mc=true}}Y.setCookie(Qb,this.Xb,Lc)};mboxSession.prototype.getId=function(){return this.Xb};mboxSession.prototype.forceId=function(Nc){this.Xb=Nc;this.Y.setCookie(this.Qb,this.Xb,this.Lc)};mboxPC=function(Qb,Lc,Y){this.Qb=Qb;this.Lc=Lc;this.Y=Y;this.Xb=typeof mboxForcePCId!="undefined"?mboxForcePCId:
Y.getCookie(Qb);if(this.Xb!=null)Y.setCookie(Qb,this.Xb,Lc)};mboxPC.prototype.getId=function(){return this.Xb};mboxPC.prototype.forceId=function(Nc){if(this.Xb!=Nc){this.Xb=Nc;this.Y.setCookie(this.Qb,this.Xb,this.Lc);return true}return false};mboxGetPageParameter=function(w){var l=null;var Oc=new RegExp("\\?[^#]*"+w+"\x3d([^\x26;#]*)");var Pc=Oc.exec(document.location);if(Pc!=null&&Pc.length>=2)l=Pc[1];return l};mboxSetCookie=function(w,x,rb){return mboxFactoryDefault.getCookieManager().setCookie(w,
x,rb)};mboxGetCookie=function(w){return mboxFactoryDefault.getCookieManager().getCookie(w)};mboxCookiePageDomain=function(){var uc=/([^:]*)(:[0-9]{0,5})?/.exec(document.location.host)[1];var Qc=/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/;if(!Qc.exec(uc)){var Rc=/([^\.]+\.[^\.]{3}|[^\.]+\.[^\.]+\.[^\.]{2})$/.exec(uc);if(Rc){uc=Rc[0];if(uc.indexOf("www.")==0)uc=uc.substr(4)}}return uc?uc:""};mboxShiftArray=function(Sc){var l=new Array;for(var y=1;y<Sc.length;y++)l[l.length]=Sc[y];return l};mboxGenerateId=
function(){return(new Date).getTime()+"-"+Math.floor(Math.random()*999999)};mboxScreenHeight=function(){return screen.height};mboxScreenWidth=function(){return screen.width};mboxBrowserWidth=function(){return window.innerWidth?window.innerWidth:document.documentElement?document.documentElement.clientWidth:document.body.clientWidth};mboxBrowserHeight=function(){return window.innerHeight?window.innerHeight:document.documentElement?document.documentElement.clientHeight:document.body.clientHeight};mboxBrowserTimeOffset=
function(){return-(new Date).getTimezoneOffset()};mboxScreenColorDepth=function(){return screen.pixelDepth};if(typeof mboxVersion=="undefined"){var mboxVersion=53;var mboxFactories=new mboxMap;var mboxFactoryDefault=new mboxFactory("citicorpcreditservic.tt.omtrdc.net","citicorpcreditservic","default")}if(mboxGetPageParameter("mboxDebug")!=null||mboxFactoryDefault.getCookieManager().getCookie("debug")!=null){setTimeout(function(){if(typeof mboxDebugLoaded=="undefined")alert("Could not load the remote debug.\nPlease check your connection"+
" to Test\x26amp;Target servers")},60*60);document.write("\x3c"+"scr"+'ipt language\x3d"Javascript1.2" src\x3d'+'"//admin6.testandtarget.omniture.com/admin/mbox/mbox_debug.jsp?mboxServerHost\x3dciticorpcreditservic.tt.omtrdc.net'+'\x26clientCode\x3dciticorpcreditservic"\x3e\x3c'+"/scr"+"ipt\x3e")}mboxScPluginFetcher=function(r,Tc){this.r=r;this.Tc=Tc};mboxScPluginFetcher.prototype.Uc=function(L){L.setBasePath("/m2/"+this.r+"/sc/standard");this.Vc(L);var u=L.buildUrl();u+="\x26scPluginVersion\x3d1";
return u};mboxScPluginFetcher.prototype.Vc=function(L){var Wc=["dynamicVariablePrefix","visitorID","vmk","ppu","charSet","visitorNamespace","cookieDomainPeriods","cookieLifetime","pageName","currencyCode","variableProvider","channel","server","pageType","transactionID","purchaseID","campaign","state","zip","events","products","linkName","linkType","resolution","colorDepth","javascriptVersion","javaEnabled","cookiesEnabled","browserWidth","browserHeight","connectionType","homepage","pe","pev1","pev2",
"pev3","visitorSampling","visitorSamplingGroup","dynamicAccountSelection","dynamicAccountList","dynamicAccountMatch","trackDownloadLinks","trackExternalLinks","trackInlineStats","linkLeaveQueryString","linkDownloadFileTypes","linkExternalFilters","linkInternalFilters","linkTrackVars","linkTrackEvents","linkNames","lnk","eo"];for(var y=0;y<Wc.length;y++)this.Xc(Wc[y],L);for(var y=1;y<=75;y++){this.Xc("prop"+y,L);this.Xc("eVar"+y,L);this.Xc("hier"+y,L)}};mboxScPluginFetcher.prototype.Xc=function(w,
L){var x=this.Tc[w];if(typeof x==="undefined"||x===null||x===""||typeof x==="object")return;L.addParameter(w,x)};mboxScPluginFetcher.prototype.cancel=function(){};mboxScPluginFetcher.prototype.fetch=function(L){L.setServerType(this.getType());var u=this.Uc(L);this.M=document.createElement("script");this.M.src=u;document.body.appendChild(this.M)};mboxScPluginFetcher.prototype.getType=function(){return"ajax"};function mboxLoadSCPlugin(Tc){if(!Tc)return null;Tc.m_tt=function(Tc){var Yc=Tc.m_i("tt");
Yc.W=true;Yc.r="citicorpcreditservic";Yc["_t"]=function(){if(!this.isEnabled())return;var mb=this._c();if(mb){var kc=new mboxScPluginFetcher(this.r,this.s);mb.setFetcher(kc);mb.load()}};Yc.isEnabled=function(){return this.W&&mboxFactoryDefault.isEnabled()};Yc._c=function(){var qb=this.ad();var Ub=document.createElement("DIV");return mboxFactoryDefault.create(qb,new Array,Ub)};Yc.ad=function(){var bd=this.s.events&&this.s.events.indexOf("purchase")!=-1;return"SiteCatalyst: "+(bd?"purchase":"event")}};
return Tc.loadModule("tt")}mboxVizTargetUrl=function(qb){if(!mboxFactoryDefault.isEnabled())return;var L=mboxFactoryDefault.getUrlBuilder().clone();L.setBasePath("/m2/"+"citicorpcreditservic"+"/viztarget");L.addParameter("mbox",qb);L.addParameter("mboxId",0);L.addParameter("mboxCount",mboxFactoryDefault.getMboxes().length()+1);var Gb=new Date;L.addParameter("mboxTime",Gb.getTime()-Gb.getTimezoneOffset()*6E4);L.addParameter("mboxPage",mboxGenerateId());var s=mboxShiftArray(arguments);if(s&&s.length>
0)L.addParameters(s);L.addParameter("mboxDOMLoaded",mboxFactoryDefault.isDomLoaded());mboxFactoryDefault.setVisitorIdParameters(L,qb);return L.buildUrl()};TNT.createGlobalMbox=function(){var cd="target-global-mbox";var dd="".length===0;var ed="";var fd;if(dd){ed="mbox-"+cd+"-"+mboxGenerateId();fd=document.createElement("div");fd.className="mboxDefault";fd.id=ed;fd.style.visibility="hidden";fd.style.display="none";mboxFactoryDefault.addOnLoad(function(){document.body.insertBefore(fd,document.body.firstChild)})}var gd=
mboxFactoryDefault.create(cd,TNT.a.b(),ed);if(gd!=null)gd.load()};document.write('\x3cscript src\x3d"'+document.location.protocol+'//cdn.tt.omtrdc.net/cdn/target.js"\x3e\x3c/script\x3e');mbox.prototype.zload=mbox.prototype.load;mbox.prototype.load=function(){var SC_MBOX="SiteCatalyst: event";var mboxname=this.getName();if(mboxname!=SC_MBOX||mboxname==SC_MBOX&&mboxFactoryDefault.getMboxes().get(mboxname).length()<=1)this.zload.apply(this,Array.prototype.slice.call(arguments))};mboxScPluginFetcher.prototype.Xc=
function(w,L){var x=this.Tc[w];if(typeof x==="undefined"||x===null||x==="")return;if(!w.match("^(eVar53|prop55|linkInternalFilters|linkTrackVars|linkTrackEvents|linkDownloadFileTypes)$"))L.addParameter(w,x)};TNT.createGlobalMbox()}if(typeof TNT!="undefined")window.TNT=TNT||{};if(typeof mboxCopyright!="undefined")window.mboxCopyright=mboxCopyright||"error";if(typeof mboxVersion!="undefined")window.mboxVersion=mboxVersion||"error";if(typeof mboxFactories!="undefined")window.mboxFactories=mboxFactories||
{};if(typeof mboxFactoryDefault!="undefined")window.mboxFactoryDefault=mboxFactoryDefault||{};if(typeof mboxVizTargetUrl!="undefined")window.mboxVizTargetUrl=mboxVizTargetUrl||function(){};if(typeof mboxLoadSCPlugin!="undefined")window.mboxLoadSCPlugin=mboxLoadSCPlugin||function(){}}catch(n){window.TNT={},window.mboxError=n,window.mboxCopyright="error",window.mboxFactories={},window.mboxFactoryDefault={},window.mboxVizTargetUrl=function(){},mboxCreate=function(){},mboxDefine=function(){},mboxUpdate=
function(){},mboxLoadSCPlugin=function(){}}},1855922,358910);Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;if(typeof window._citiData!="undefined")Bootstrapper.getExtraParams=function(){var a={"page_def":window._citiData.pageDef};return a}},1124213,354602);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.propertyWatcher=function(options){var _private={watchers:[]},_public={};_private.options=options||{};_private.options.interval=_private.options.interval||50;_private.Watcher=function(propertyFn,options){var _public={};_public.propertyFn=propertyFn;_public.lastValue=undefined;_public.options=options;_public.change=function(oldVal,newVal){};return _public};_private.doChecks=
function(){for(var i=0;i<_private.watchers.length;i++){var w=_private.watchers[i],p=w.propertyFn?w.propertyFn():null;if(w.lastValue!=p){w.change(w.lastValue,p);w.lastValue=p}}_private.resetTimer()};_private.resetTimer=function(){window.setTimeout(function(){_private.doChecks()},_private.options.interval)};_private.addWatcher=function(fn,options){var w=_private.Watcher(fn,options);_private.watchers.push(w);return w};_public={create:_private.addWatcher};_private.doChecks();return _public}()},1482837,
373773);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();